class ServiceNames {
  List<String> hairServices = <String>[
    'Haircut',
    'Hair Color',
    'Highlights',
    'Balayage',
    'Ombre',
    'Hair Extensions',
    'Perms',
    'Straightening/Relaxing',
    'Keratin Treatment',
    'Scalp Treatment',
    'Deep Conditioning',
    'Hair Styling',
    'Updos',
    'Braiding',
    'Beard Trim',
    'Shaving',
    'Hair and Scalp Massage',
    'Hair Threading',
    'Hair Glossing',
    'Hair Glazing',
  ];
  List<String> makeupServices = <String>[
    'Makeup Application',
    'Bridal Makeup',
    'Airbrush Makeup',
    'Special Effects Makeup',
    'Editorial/Fashion Makeup',
    'Glamour Makeup',
    'Natural Makeup',
    'Evening Makeup',
    'Prom Makeup',
    'Pageant Makeup',
    'Stage Makeup',
    'Photoshoot Makeup',
    'TV/Film Makeup',
    'Theatrical Makeup',
    'Fantasy Makeup',
    'Face Painting',
    'Makeup Lessons/Tutorials',
    'Makeup Consultations',
  ];
  List<String> spaServices = <String>[
    'Massage Therapy',
    'Body Scrub',
    'Hydrotherapy',
    'Reflexology',
    'Reiki',
    'Acupuncture',
    'Cupping Therapy',
    'Aromatherapy',
    'Meditation and Mindfulness',
    'Body Contouring',
    'Ear Candling',
    'Holistic Healing',
  ];
  List<String> nailsServices = <String>[
    'Manicure',
    'Pedicure',
    'Nail Extensions',
    'Nail Art',
    'Nail Repair',
    'Nail Removal',
    'Nail Buffing and Shaping',
    'Cuticle Care',
    'Nail Whitening',
    'Nail Strengthening',
    'Nail Hardening',
    'Nail Conditioning',
    'Nail Polish Applications',
    'Nail Polish Removal',
    'Paraffin Wax Treatment for Hands and Feet',
    'Moisturizing Treatments',
    'Nail and Cuticle Oil Application',
    'Nail Extensions Refill',
    'Nail Design Consultations',
  ];
  List<String> lashesServices = <String>[
    'Eyelash Extensions',
    'Lash Lift',
    'Lash Tinting',
    'Eyelash Removal',
    'Eyelash Refills',
    'Eyelash Extension Correction',
    'Eyelash Extension Consultations',
    'Bottom Lash Extensions',
    'Eyelash Extension Removal',
    'Lash Health Treatments',
    'Eyelash Serum Application',
    'Lash Growth Treatments',
    'Eyelash Extension Aftercare Instructions',
    'Eyelash Extension Fills',
    'Eyelash Extension Touch-ups',
    'Custom Eyelash Design',
  ];
  List<String> waxServices = <String>[
    'Eyebrow Waxing',
    'Lip Waxing',
    'Chin Waxing',
    'Full Face Waxing',
    'Underarm Waxing',
    'Arm Waxing',
    'Leg Waxing',
    'Bikini Waxing',
    'Chest Waxing',
    'Back Waxing',
    'Stomach Waxing',
    'Shoulder Waxing',
    'Neck Waxing',
    'Buttocks Waxing',
    'Nose Waxing',
    'Ear Waxing',
    'Full Body Waxing',
    'Male Waxing Services',
    'Female Intimate Waxing',
  ];
}
